ALTER TABLE users
    ADD COLUMN IF NOT EXISTS name       VARCHAR(50),
    ADD COLUMN IF NOT EXISTS birthday   DATE,
    ADD COLUMN IF NOT EXISTS age        SMALLINT,
    ADD COLUMN IF NOT EXISTS job        VARCHAR(50);
